version: '3' 
services:
  gateway:
    image: mrodriguezmgm01/zuul-api-gateway:0.0.1
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    ports: 
      - "9090:8080" 
    depends_on:
      - eureka
    restart: always

  eureka:
    image: mrodriguezmgm01/eureka:0.0.1
    ports: 
      - 8761:8761
    restart: always

  accountbank:
    image: mrodriguezmgm01/account_bank:0.0.1
    environment:
      - SPRING_DATA_ELASTICSEARCH_CLUSTER-NODES=elasticsearch:9300
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    ports:
      - 8081:8080
      - 8082:8081
    depends_on:
      - elasticsearch
      - eureka
    restart: always

  customerbank:
    image: mrodriguezmgm01/customer_bank:0.0.1
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    ports:
      - 8080:8080
      - 8083:8081
    depends_on:
      - rabbitmq
      - eureka
    restart: always

  rabbitmq:
    image: rabbitmq:3.6.12-management-alpine
    ports:
      - 15672:15672
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq/mnesia
    restart: always

  elasticsearch:
    image: elasticsearch:2.4.6-alpine
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./data/elasticsearch/master:/usr/share/elasticsearch/data
    restart: always

  elasticsearch_slave:
    image: elasticsearch:2.4.6-alpine
    volumes:
      - ./data/elasticsearch/slave:/usr/share/elasticsearch/data
    depends_on:
      - elasticsearch
    command: elasticsearch --discovery.zen.ping.unicast.hosts=elasticsearch
    restart: always